// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNiGKUCV-2A87WTQFNvLPnPL7BOy_I8qY',
    appId: '1:964411158459:web:eef727b29cb1e1991c1e9e',
    messagingSenderId: '964411158459',
    projectId: 'insta-share-dfbcb',
    authDomain: 'insta-share-dfbcb.firebaseapp.com',
    storageBucket: 'insta-share-dfbcb.appspot.com',
    measurementId: 'G-075ZHR2DFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLzqUK8lyriG510iLrTyzhO7kU35RatQk',
    appId: '1:964411158459:android:9123551ea57e20811c1e9e',
    messagingSenderId: '964411158459',
    projectId: 'insta-share-dfbcb',
    storageBucket: 'insta-share-dfbcb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG3Gi4DuN9Jv_QKOwWxKzG0UoYLlA3GiE',
    appId: '1:964411158459:ios:b2ba4b9707167fac1c1e9e',
    messagingSenderId: '964411158459',
    projectId: 'insta-share-dfbcb',
    storageBucket: 'insta-share-dfbcb.appspot.com',
    iosBundleId: 'com.example.instaShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG3Gi4DuN9Jv_QKOwWxKzG0UoYLlA3GiE',
    appId: '1:964411158459:ios:b2ba4b9707167fac1c1e9e',
    messagingSenderId: '964411158459',
    projectId: 'insta-share-dfbcb',
    storageBucket: 'insta-share-dfbcb.appspot.com',
    iosBundleId: 'com.example.instaShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNiGKUCV-2A87WTQFNvLPnPL7BOy_I8qY',
    appId: '1:964411158459:web:4196770f37b639f11c1e9e',
    messagingSenderId: '964411158459',
    projectId: 'insta-share-dfbcb',
    authDomain: 'insta-share-dfbcb.firebaseapp.com',
    storageBucket: 'insta-share-dfbcb.appspot.com',
    measurementId: 'G-ZK5BV7N3RV',
  );
}
